function RCMDynamicMultiSelectModel(a){this._super(a);this.initialize()}
juic.extend(RCMDynamicMultiSelectModel,SFDefaultListModel,{initialize:function(){this._selectedItems={};this._unselectedItems={};this._totalNumberOfRecords=0;this._defaultSelectNewItems=this._selectAll=!1;this._preSelectedValues=[];this._primaryInfo={index:null,value:null,primaryDisplayText:null,getValue:function(){return this.value},getPrimaryDisplayText:function(){return this.primaryDisplayText}};this._selectedDisplayValues={};this._allSelectedDisplayValues=null},addItem:function(a,b){"undefined"!=
typeof b&&a instanceof RcmMultiSelectObjItem&&(this._items[b]=a,this._defaultSelectNewItems&&this.selectItemAtIndex(a,b),Util.arrayContains(this._preSelectedValues,a.getValue().toString())&&(this.getPreSelectedValues().splice(this.indexOf(a.getValue().toString(),this._preSelectedValues),1),this.selectItemAtIndex(a,b)),this._primaryInfo.value==a.getValue().toString()&&this.setPrimaryInfo(b,a.getValue().toString(),a.getPrimaryDisplayText()))},getCountOfItems:function(){return this._items?this._items.length:
0},indexOf:function(a,b){for(var c=b.length;c;){if(b[c-1]==a)return c-1;c--}return-1},selectIndex:function(a){if(0<=a){var b=this.get(a);this.selectItemAtIndex(b,a)}},selectItemAtIndex:function(a,b){a&&(this._selectedItems[b]=a,this._unselectedItems&&this._unselectedItems[b]&&delete this._unselectedItems[b],this.isAllSelected()&&(this._selectAll=!0),this.dispatch("selectionChanged"))},unselectIndex:function(a){if(this.get(a)){var b=this.get(a);this._selectedItems&&this._selectedItems[a]&&delete this._selectedItems[a];
this._defaultSelectNewItems&&(this._unselectedItems[a]=b);this._selectAll&&(this._selectAll=!1);this.dispatch("selectionChanged")}},removeItemFromDisplayValues:function(a){delete this._selectedDisplayValues[a]},addItemToDisplayValues:function(a){this._selectedDisplayValues[a.getValue()]=a.getPrimaryDisplayText()},isPrimary:function(a){return this._primaryInfo.value&&a==this._primaryInfo.index},setNextSelectedItemAsPrimary:function(a){if(0<this.getSelectedItemValues().length){for(var b in this._selectedItems)if(this._selectedItems.hasOwnProperty(b)){this.setPrimaryInfo(b,
this._selectedItems[b].getValue(),this._selectedItems[b].getPrimaryDisplayText());break}return this._primaryInfo.index}0<this.getPreSelectedValues().length?this.setPrimaryInfo(null,this._preSelectedValues[0],this._selectedDisplayValues[this._preSelectedValues[0]]):(this._primaryInfo.value=null,this._primaryInfo.primaryDisplayText=null);this._primaryInfo.index=null;return-1},selectAllEnabled:function(a){this._defaultSelectNewItems=this._selectAll=a},getTotalNumberOfRecords:function(){return this._totalNumberOfRecords},
setSelectedDisplayValues:function(a){a&&(this._selectedDisplayValues=a)},getSelectedDisplayValues:function(){return this._selectedDisplayValues},setPreSelectedValues:function(a){a&&(this._preSelectedValues=a)},getPreSelectedValues:function(){return this._preSelectedValues},setPrimaryInfo:function(a,b,c){this._primaryInfo.index=a;""!==b&&(this._primaryInfo.value=b);this._primaryInfo.primaryDisplayText=c;this.removeItemFromDisplayValues(b)},getPrimaryInfo:function(){return this._primaryInfo},getCountOfItemsSelected:function(){return this._defaultSelectNewItems?
this.getTotalNumberOfRecords()-this.getCountOfUnSelectedItems():this.getPreSelectedValues().length+this.getCountOfSelectedItems()},isAllSelected:function(){return this._selectAll||0<this.getTotalNumberOfRecords()&&this.getCountOfSelectedItems()+this.getPreSelectedValues().length==this.getTotalNumberOfRecords()},createSelectedObjItems:function(a){for(var b in a)a.hasOwnProperty(b)&&(null!=this._primaryInfo.value&&this._primaryInfo.value==b?this._primaryInfo.primaryDisplayText=a[b]:this._selectedDisplayValues[b]=
a[b])},createSelectedAllObjItems:function(a){this._selectedDisplayValues={};for(var b in a)a.hasOwnProperty(b)&&(null!=this._primaryInfo.value&&this._primaryInfo.value==b?this._primaryInfo.primaryDisplayText=a[b]:this._selectedDisplayValues[b]=a[b]);if(!this.isAllSelected()&&0==this.getCountOfUnSelectedItems())this._selectedDisplayValues={};else if(!this.isAllSelected())for(b in a=this.getUnselectedItemValues(),a)this.removeItemFromDisplayValues(a[b])},setAllSelectedDisplayValues:function(a){this._allSelectedDisplayValues=
a},setTotalNumberOfRecords:function(a){0<a&&!this._totalNumberOfRecords&&(this._totalNumberOfRecords=a)},getCountOfSelectedItems:function(){var a=0,b;for(b in this._selectedItems)this._selectedItems.hasOwnProperty(b)&&a++;return a},getCountOfUnSelectedItems:function(){var a=0,b;for(b in this._unselectedItems)this._unselectedItems.hasOwnProperty(b)&&a++;return a},isIndexSelected:function(a){return this._selectedItems&&this._selectedItems[a]?!0:!1},getSelectedItemValues:function(){var a=[],b;for(b in this._selectedItems)this._selectedItems.hasOwnProperty(b)&&
a.push(this._selectedItems[b].getValue());return a},getSelectedItems:function(){var a=[],b;for(b in this._selectedItems)this._selectedItems.hasOwnProperty(b)&&a.push(this._selectedItems[b]);return a},getUnselectedItemValues:function(){var a=[],b;for(b in this._unselectedItems)this._unselectedItems.hasOwnProperty(b)&&a.push(this._unselectedItems[b].getValue());return a},getSelectedIndices:function(){var a=[],b;for(b in this._selectedItems)this._selectedItems.hasOwnProperty(b)&&a.push(this._selectedItems[b]);
return a},selectAll:function(){for(var a=0;a<this.getItems().length;a++)this.getItems()[a]&&(this._selectedItems[a]=this.getItems()[a]);this._unselectedItems={};this.selectAllEnabled(!0);this.dispatch("selectionChanged")},unselectAll:function(){this._selectedItems={};this._unselectedItems={};this._preSelectedValues=[];this._primaryInfo.value=null;this._primaryInfo.index=null;this._primaryInfo.primaryDisplayText=null;this.selectAllEnabled(!1);this._selectedDisplayValues={};this.dispatch("selectionChanged")},
clear:function(){this._selectedItems={};this._unselectedItems={};this.selectAllEnabled(!1);this._totalNumberOfRecords=0;this._preSelectedValues=[];this._primaryInfo.value=null;this._primaryInfo.index=null;this._primaryInfo.primaryDisplayText=null;this._selectedDisplayValues={};this._allSelectedDisplayValues=null;this._items=[];this.dispatch("selectionChanged")}});function RcmMultiSelectObjItem(a){this.setValue(a.id);this.setText(a.name);this.setPrimaryDisplayText(a.primaryDisplayText)}
RcmMultiSelectObjItem.prototype=function(){return{setValue:function(a){this._value=a},getValue:function(){return this._value},setText:function(a){this._text=a},getText:function(a){return this._text},setPrimaryDisplayText:function(a){this._primaryDisplayText=a},getPrimaryDisplayText:function(){return this._primaryDisplayText},toString:function(){return this._text}}}();